# * dataset parameters
# * FLIR_ADAS_1_3 Dataset - num_classes 91
# dataset_root: "/home/osama/Programs/mmodetect/FLIR_ADAS_1_3/"
# annotations_folder: ""
# m1_train_annotations_file: "train/annotations/test_annotations.json"
# m2_train_annotations_file: "train/annotations/aligned_thermal_annotations.json"
# m1_train_images_folder: "train"
# m2_train_images_folder: "train"
# m1_val_annotations_file: "val/annotations/test_annotations.json"
# m2_val_annotations_file: "val/annotations/aligned_thermal_annotations.json"
# m1_val_images_folder: "val"
# m2_val_images_folder: "val"

# * Balloon dataset - num_classes 1
# dataset_root: "./custom/"
# annotations_folder: "annotations"
# m1_train_annotations_file: "custom_train.json"
# m2_train_annotations_file: "custom_train.json"
# m1_train_images_folder: "rgb/train2017"
# m2_train_images_folder: "ir/train2017"
# m1_val_annotations_file: "custom_val.json"
# m2_val_annotations_file: "custom_val.json"
# m1_val_images_folder: "rgb/val2017"
# m2_val_images_folder: "ir/val2017"

# * Sample Dataset
# dataset_root: "./"
# dataset_name: "sample_dataset"
# annotations_folder: "annotations"
# m1_train_annotations_file: "RGB_26May2021_14h19m_coco.json"
# m2_train_annotations_file: "Thermal_26May2021_14h19m_coco.json"
# m1_train_images_folder: "train/m1"
# m2_train_images_folder: "train/m2"
# m1_val_annotations_file: "RGB_26May2021_14h19m_coco.json"
# m2_val_annotations_file: "Thermal_26May2021_14h19m_coco.json"
# m1_val_images_folder: "val/m1"
# m2_val_images_folder: "val/m2"

# # * L515-dataset - num_classes 7
dataset_root: "./datasets"
dataset_name: "l515_dataset"
annotations_folder: ""
m1_train_annotations_file: "l515-29Apr2021_12h20-indoor-train-rgb-coco.json"
m2_train_annotations_file: "l515-29Apr2021_12h20-indoor-train-infra-coco.json"
m1_train_images_folder: ""
m2_train_images_folder: ""
m1_val_annotations_file: "l515-29Apr2021_12h20-indoor-test-rgb-coco.json"
m2_val_annotations_file: "l515-29Apr2021_12h20-indoor-test-infra-coco.json"
m1_val_images_folder: ""
m2_val_images_folder: ""
